CREATE TABLE IF NOT EXISTS qna_reports (
    message_id TEXT PRIMARY KEY REFERENCES qna_messages(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);
